export const userinfo = {
  userName: 'User Name', // 이름
  birth: '1999.01.27', // 생일
  point: 150, // 적립 포인트
  isProfile: true, // 프로필사진여부
};

export const countryArea = {
  area1: [
    {label: '서울특별시', value: '서울특별시'},
    {label: '경기도', value: '경기도'},
    {label: '인천광역시', value: '인천광역시'},
    {label: '부산광역시', value: '부산광역시'},
    {label: '대구광역시', value: '대구광역시'},
    {label: '광주광역시', value: '광주광역시'},
    {label: '대전광역시', value: '대전광역시'},
    {label: '울산광역시', value: '울산광역시'},
    {label: '세종특별자치시', value: '세종특별자치시'},
    {label: '강원도', value: '강원도'},
    {label: '충청북도', value: '충청북도'},
    {label: '충청남도', value: '충청남도'},
    {label: '전라북도', value: '전라북도'},
    {label: '전라남도', value: '전라남도'},
    {label: '경상북도', value: '경상북도'},
    {label: '경상남도', value: '경상남도'},
    {label: '제주특별자치도', value: '제주특별자치도'},
  ],
  area2: [
    {label: '종로구', value: '서울특별시'},
    {label: '중구', value: '경기도'},
    {label: '용산구', value: '인천광역시'},
    {label: '성동구', value: '부산광역시'},
    {label: '대구광역시', value: '대구광역시'},
    {label: '광주광역시', value: '광주광역시'},
    {label: '대전광역시', value: '대전광역시'},
    {label: '울산광역시', value: '울산광역시'},
    {label: '세종특별자치시', value: '세종특별자치시'},
    {label: '강원도', value: '강원도'},
    {label: '충청북도', value: '충청북도'},
    {label: '충청남도', value: '충청남도'},
    {label: '전라북도', value: '전라북도'},
    {label: '전라남도', value: '전라남도'},
    {label: '경상북도', value: '경상북도'},
    {label: '경상남도', value: '경상남도'},
    {label: '제주특별자치도', value: '제주특별자치도'},
    // '종로구',
    // '중구',
    // '용산구',
    // '성동구',
    // '광진구',
    // '동대문구',
    // '중랑구',
    // '성북구',
    // '강북구',
    // '도봉구',
    // '노원구',
    // '은평구',
    // '서대문구',
    // '마포구',
    // '양천구',
    // '강서구',
    // '구로구',
    // '금천구',
    // '영등포구',
    // '동작구',
    // '관악구',
    // '서초구',
    // '강남구',
    // '송파구',
    // '강동구',
  ],
};
